### ISSUE TITLE
requesting attachments of documents

### ISSUE THREAD

**Issue by karthikeyan-velayutham-s** [karthikeyan-velayutham/whatsappdevelopment#6]
dear [karthikeyan]
![login page](https://github.com/karthikeyan-velayutham/whatsappdevelopment/assets/153998217/8348cda8-634e-437b-af3e-2e83ec7c5027)

it will be great if the app is capable of attaching the document as well

**Comment by karthikeyan-velayutham** [comment]
we are working on it , we will add and let you know

**Comment by karthikeyan-velayutham** [comment]
added the feature
